CREATE TABLE sensor_data (timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP PRIMARY KEY, temperature DECIMAL(10,1) NOT NULL, humidity DECIMAL(10,1) NOT NULL );
CREATE TABLE alarms( id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50),
measure VARCHAR(40),
min_value DECIMAL(10,1),
max_value DECIMAL(10,1),
enabled INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
tel VARCHAR(10),
ring_enabled INTEGER);
